config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: "tasks#index"

  get 'tasks/new', to: 'tasks#new', as: :new_task

  get 'tasks/:id', to: 'tasks#show', as: :task

  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  scope :count_done, -> { where(done: false).count }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def task_params
    params.require(:task).permit(:name, :done, :urgency)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :urgency %>
  <%= f.text_field :urgency %>

  <%= f.radio_button(:done, true) %>
  <%= f.label(:done, "Done... 💪🏽") %>
  <%= f.radio_button(:done, false) %>
  <%= f.label(:done, "False... 💩") %>


  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit the details of your task</h1>

<h2> The task you wish to edit is: </h2>
<h3>Task name:<%= @task.name %></h3>
<p>Task status:<%= @task.done %></p>
<p>Your task has an urgency rating of <%= @task.urgency %></p>

<%= render 'form' %>

<p><button><%= link_to "Back to all tasks", tasks_path %></button></p>

app/views/tasks/index.html.erb
<h1>Your personal task manager <%= "🐙" * @tasks.count_done %></h1>

<ol>
<% @tasks.each do |task| %>
  <li> 📌 <%= task.name %>
    <% if task.done == true %>
      <span>Good job! 💪🏽 "Changed your mind? You can <%= link_to "edit", edit_task_path(task) %>here</span>
    <% else %>
      <strong>(<%= (task.urgency)%>)</strong> </li>
      <ul>
        <li><%=link_to "Show this task", task_path(task) %></li>
        <li><%=link_to "Edit this task", edit_task_path(task) %></li>
        <li><%=link_to "Delete this task", delete_task_path(task), method: :delete %>
      </li>
    <% end %>
    </ul>
<% end %>
</ol>


<p> ✏️ <button><%= link_to "Add a new task to your task list", new_task_path %></button></p>

app/views/tasks/new.html.erb
<h1>Enter details of your new task</h1>

<%= render 'form' %>

<p><button><%= link_to "Back to all tasks", tasks_path %></button></p>

app/views/tasks/show.html.erb
<h1>Show task</h1>
<h2>Task name:<%= @task.name %></h2>
<h3>Task status:<%= @task.done %></h3>
<p>Your task has an urgency rating of <%= @task.urgency %></p>

<p><button><%= link_to "Back to all tasks", tasks_path %></button></p>